# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jin draws
author: Jin Ting
author_description: A photography and doodling neophyte.
email: tjt_0610@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  A photography and doodling neophyte.
baseurl: "/jindraws" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty

# Pagination
paginate: 3

# Sass
sass:
    style: :compressed

prose:
    media: "img/"
    siteurl: "https://jintinggg.github.io"
